
select 
"U_BGT_CardCode",
"U_BGT_CardName",
"U_BGT_CodHolding",
"U_BGT_NomHolding",
"U_BGT_CntcPerson",
"U_BGT_DestObra",
"U_BGT_Territor",
"U_BGT_DocNumOC",
"U_BGT_DocEntryOC",
"U_BGT_PriceList",
"U_BGT_CodSurc",
"U_BGT_Project",
"U_BGT_CodComis",
"U_BGT_Status",
"U_BGT_DocDateDesp",
"U_BGT_DurCont",
"U_BGT_DocEntryOF",
"U_BGT_Transporte",
"U_BGT_NumOport",
"U_BGT_ActRel",
"U_BGT_Categor",
"U_BGT_PerFact",
"U_BGT_Comments",
"U_BGT_ValRepEqOb",
"U_BGT_ValRepCont",
"U_BGT_ValGarant",
"U_BGT_SubPesObra",
"U_BGT_SubPesEnt",
"U_BGT_TipCalc",
"U_BGT_DocNumOF",
"U_BGT_DirecFE",
"U_BGT_OrdComp",
"U_BGT_Owner",
"U_BGT_SlpCode",
"U_BGT_DistObra",
"U_BGT_SlpName",
"U_BGT_OwnerId",
"U_BGT_ProjectName",
"U_BGT_CicloFact",
"U_BGT_NomComis", 
"Series",
(select CONCAT (concat("lastName", ','), "firstName") as "OwnerN" from "OHEM" where "userId"=(select "USERID" from  "OUSR" where "USER_CODE"='{1}')) as "OwnerN",
(select "empID"  from "OHEM" where "userId"=1) as "OwnerD"
 from "@BGT_OCTR"
 WHERE "DocNum" = '{0}'